t = -10:10;


% Part A
% Generate a Unit Impulse Signal delta[n].
% Use the cumulative summation function (cumsum) on your impulse signal array to obtain the corresponding Unit Step Signal u[n].
imp = (t==0);
unit = cumsum(imp)
stem(t,unit);


% Part B
% Generate a Unit Step Signal u[n].
% Use the cumulative summation function on your step signal to obtain the Ramp Signal r[n].
unit = (t>=0);
ramp = (cumsum(unit)-unit);
stem(t,ramp);


% Part C
% Generate a Ramp Signal r[n].
% Use the first difference operation on your ramp signal to recover the Unit Step Signal u[n].
% Verify the mathematical relationship: u[n] = r[n] - r[n-1]
unit = (t >= 0);
ramp = cumsum(unit)-unit;
unit = zeros(size(ramp));
unit(2:end) = ramp(2:end) - ramp(1:end-1);
stem(t-1, unit);



% Brief text discussion verifying that my programmed outputs match the theoretical mathematical definitions.

% The programmed outputs for the Unit Impulse, Unit Step, and Ramp signals match the theoretical mathematical definitions. The Unit Impulse signal is generated as a single non-zero value at n=0, which is consistent with the definition of an impulse. The Unit Step signal is obtained by taking the cumulative sum of the impulse signal, resulting in a step function that transitions from 0 to 1 at n=0. The Ramp signal is derived from the cumulative sum of the Unit Step signal, producing a linear increase starting from n=0. Additionally, applying the first difference operation to the Ramp signal successfully recovers the Unit Step signal, confirming the mathematical relationship u[n] = r[n] - r[n-1].



% QnA:

% Q: How is a Unit Step generated from an Impulse?
% Ans: A Unit Step signal is generated by taking the cumulative sum of the Unit Impulse signal.

% Q: How is a Ramp generated from a Step?
% Ans: A Ramp signal is generated by taking the cumulative sum of the Unit Step signal.

% Q: Why is cumulative summation important in DSP?
% Ans: Cumulative summation is important in DSP because it allows for the generation of signals that represent the integral of other signals, which is useful in various signal processing applications.

% Q: What happens when the difference operation is applied to a Ramp?
% Ans: When the difference operation is applied to a Ramp signal, it recovers the Unit Step signal, confirming the mathematical relationship u[n] = r[n] - r[n-1].